<?php
namespace Home\Controller;
use Common\Controller\CommonController;
use Common\Lib\Tools;
use Common\Model\ClientModel;
use Common\Model\RedshareModel;

class ComController extends  CommonController{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub


    }
    public function topList(){
        $page=I('get.page');
        $len=I('get.limit');
        if(!$page){
            $page=1;
        }
        if(!$len){
            $len=10;
        }
        $start=($page-1)*$limit;
        $this->contentName='toplist';

        $this->outJson($this->getToplist($start,$len),1);
    }
    private function getToplist(){
        $rm=new RedshareModel();
        $result=$rm->getTopList();
        foreach ($result as $k=>$v){
            $result[$k]['time']=Tools::timeFormat2($v['time']);
        }

        return $result;
    }

    /**
     * 首页多少人砍价数字
     */
    public function getAllNum(){
        $mc=new ClientModel();
        $map['openid']=array('neq','');
        $ret=$mc->where($map)->select();
        $num=count($ret);
        $num+=15800;
        $this->outJson(array('num'=>$num));
    }
}